# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\aldo\Documents\GitHub\Proyecto_Concesionario\Agregarvehiculo.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dialogo_vehculo(object):
    def setupUi(self, dialogo_vehculo):
        dialogo_vehculo.setObjectName("dialogo_vehculo")
        dialogo_vehculo.setWindowModality(QtCore.Qt.WindowModal)
        dialogo_vehculo.resize(516, 519)
        self.centralwidget = QtWidgets.QWidget(dialogo_vehculo)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.leciudad_7 = QtWidgets.QLineEdit(self.centralwidget)
        self.leciudad_7.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leciudad_7.sizePolicy().hasHeightForWidth())
        self.leciudad_7.setSizePolicy(sizePolicy)
        self.leciudad_7.setObjectName("leciudad_7")
        self.gridLayout.addWidget(self.leciudad_7, 11, 2, 1, 1)
        self.bguardar = QtWidgets.QPushButton(self.centralwidget)
        self.bguardar.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bguardar.sizePolicy().hasHeightForWidth())
        self.bguardar.setSizePolicy(sizePolicy)
        self.bguardar.setAutoDefault(False)
        self.bguardar.setDefault(False)
        self.bguardar.setFlat(False)
        self.bguardar.setObjectName("bguardar")
        self.gridLayout.addWidget(self.bguardar, 12, 1, 1, 2)
        self.lbplaca = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbplaca.sizePolicy().hasHeightForWidth())
        self.lbplaca.setSizePolicy(sizePolicy)
        self.lbplaca.setObjectName("lbplaca")
        self.gridLayout.addWidget(self.lbplaca, 1, 0, 1, 1)
        self.lbmarca = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbmarca.sizePolicy().hasHeightForWidth())
        self.lbmarca.setSizePolicy(sizePolicy)
        self.lbmarca.setObjectName("lbmarca")
        self.gridLayout.addWidget(self.lbmarca, 2, 0, 1, 1)
        self.leapellido = QtWidgets.QLineEdit(self.centralwidget)
        self.leapellido.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leapellido.sizePolicy().hasHeightForWidth())
        self.leapellido.setSizePolicy(sizePolicy)
        self.leapellido.setObjectName("leapellido")
        self.gridLayout.addWidget(self.leapellido, 2, 2, 1, 1)
        self.lbdireccion = QtWidgets.QLabel(self.centralwidget)
        self.lbdireccion.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbdireccion.sizePolicy().hasHeightForWidth())
        self.lbdireccion.setSizePolicy(sizePolicy)
        self.lbdireccion.setObjectName("lbdireccion")
        self.gridLayout.addWidget(self.lbdireccion, 3, 0, 1, 2)
        self.ledireccion = QtWidgets.QLineEdit(self.centralwidget)
        self.ledireccion.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ledireccion.sizePolicy().hasHeightForWidth())
        self.ledireccion.setSizePolicy(sizePolicy)
        self.ledireccion.setObjectName("ledireccion")
        self.gridLayout.addWidget(self.ledireccion, 3, 2, 1, 1)
        self.lbcilindraje = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbcilindraje.sizePolicy().hasHeightForWidth())
        self.lbcilindraje.setSizePolicy(sizePolicy)
        self.lbcilindraje.setObjectName("lbcilindraje")
        self.gridLayout.addWidget(self.lbcilindraje, 4, 0, 1, 1)
        self.leciudad = QtWidgets.QLineEdit(self.centralwidget)
        self.leciudad.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leciudad.sizePolicy().hasHeightForWidth())
        self.leciudad.setSizePolicy(sizePolicy)
        self.leciudad.setObjectName("leciudad")
        self.gridLayout.addWidget(self.leciudad, 4, 2, 1, 1)
        self.lbciudad_2 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbciudad_2.sizePolicy().hasHeightForWidth())
        self.lbciudad_2.setSizePolicy(sizePolicy)
        self.lbciudad_2.setObjectName("lbciudad_2")
        self.gridLayout.addWidget(self.lbciudad_2, 6, 0, 1, 1)
        self.lecelular = QtWidgets.QLineEdit(self.centralwidget)
        self.lecelular.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lecelular.sizePolicy().hasHeightForWidth())
        self.lecelular.setSizePolicy(sizePolicy)
        self.lecelular.setObjectName("lecelular")
        self.gridLayout.addWidget(self.lecelular, 6, 2, 1, 1)
        self.lbciudad_3 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbciudad_3.sizePolicy().hasHeightForWidth())
        self.lbciudad_3.setSizePolicy(sizePolicy)
        self.lbciudad_3.setObjectName("lbciudad_3")
        self.gridLayout.addWidget(self.lbciudad_3, 7, 0, 1, 2)
        self.leciudad_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.leciudad_3.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leciudad_3.sizePolicy().hasHeightForWidth())
        self.leciudad_3.setSizePolicy(sizePolicy)
        self.leciudad_3.setObjectName("leciudad_3")
        self.gridLayout.addWidget(self.leciudad_3, 7, 2, 1, 1)
        self.lbIdcliente = QtWidgets.QLabel(self.centralwidget)
        self.lbIdcliente.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbIdcliente.sizePolicy().hasHeightForWidth())
        self.lbIdcliente.setSizePolicy(sizePolicy)
        self.lbIdcliente.setObjectName("lbIdcliente")
        self.gridLayout.addWidget(self.lbIdcliente, 0, 0, 1, 1)
        self.lbciudad_4 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbciudad_4.sizePolicy().hasHeightForWidth())
        self.lbciudad_4.setSizePolicy(sizePolicy)
        self.lbciudad_4.setObjectName("lbciudad_4")
        self.gridLayout.addWidget(self.lbciudad_4, 8, 0, 1, 2)
        self.leciudad_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.leciudad_4.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leciudad_4.sizePolicy().hasHeightForWidth())
        self.leciudad_4.setSizePolicy(sizePolicy)
        self.leciudad_4.setObjectName("leciudad_4")
        self.gridLayout.addWidget(self.leciudad_4, 8, 2, 1, 1)
        self.lbciudad = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbciudad.sizePolicy().hasHeightForWidth())
        self.lbciudad.setSizePolicy(sizePolicy)
        self.lbciudad.setObjectName("lbciudad")
        self.gridLayout.addWidget(self.lbciudad, 5, 0, 1, 1)
        self.leciudad_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.leciudad_2.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leciudad_2.sizePolicy().hasHeightForWidth())
        self.leciudad_2.setSizePolicy(sizePolicy)
        self.leciudad_2.setObjectName("leciudad_2")
        self.gridLayout.addWidget(self.leciudad_2, 5, 2, 1, 1)
        self.lenombre = QtWidgets.QLineEdit(self.centralwidget)
        self.lenombre.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lenombre.sizePolicy().hasHeightForWidth())
        self.lenombre.setSizePolicy(sizePolicy)
        self.lenombre.setObjectName("lenombre")
        self.gridLayout.addWidget(self.lenombre, 1, 2, 1, 1)
        self.lbciudad_6 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbciudad_6.sizePolicy().hasHeightForWidth())
        self.lbciudad_6.setSizePolicy(sizePolicy)
        self.lbciudad_6.setObjectName("lbciudad_6")
        self.gridLayout.addWidget(self.lbciudad_6, 11, 0, 1, 2)
        self.leciudad_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.leciudad_5.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leciudad_5.sizePolicy().hasHeightForWidth())
        self.leciudad_5.setSizePolicy(sizePolicy)
        self.leciudad_5.setObjectName("leciudad_5")
        self.gridLayout.addWidget(self.leciudad_5, 9, 2, 1, 1)
        self.lbciudad_5 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbciudad_5.sizePolicy().hasHeightForWidth())
        self.lbciudad_5.setSizePolicy(sizePolicy)
        self.lbciudad_5.setObjectName("lbciudad_5")
        self.gridLayout.addWidget(self.lbciudad_5, 9, 0, 1, 2)
        self.lbciudad_7 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbciudad_7.sizePolicy().hasHeightForWidth())
        self.lbciudad_7.setSizePolicy(sizePolicy)
        self.lbciudad_7.setObjectName("lbciudad_7")
        self.gridLayout.addWidget(self.lbciudad_7, 10, 0, 1, 2)
        self.leciudad_6 = QtWidgets.QLineEdit(self.centralwidget)
        self.leciudad_6.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leciudad_6.sizePolicy().hasHeightForWidth())
        self.leciudad_6.setSizePolicy(sizePolicy)
        self.leciudad_6.setObjectName("leciudad_6")
        self.gridLayout.addWidget(self.leciudad_6, 10, 2, 1, 1)
        self.le_cliente = QtWidgets.QLineEdit(self.centralwidget)
        self.le_cliente.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_cliente.sizePolicy().hasHeightForWidth())
        self.le_cliente.setSizePolicy(sizePolicy)
        self.le_cliente.setObjectName("le_cliente")
        self.gridLayout.addWidget(self.le_cliente, 0, 2, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        dialogo_vehculo.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(dialogo_vehculo)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 516, 21))
        self.menubar.setObjectName("menubar")
        dialogo_vehculo.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(dialogo_vehculo)
        self.statusbar.setObjectName("statusbar")
        dialogo_vehculo.setStatusBar(self.statusbar)

        self.retranslateUi(dialogo_vehculo)
        QtCore.QMetaObject.connectSlotsByName(dialogo_vehculo)

    def retranslateUi(self, dialogo_vehculo):
        _translate = QtCore.QCoreApplication.translate
        dialogo_vehculo.setWindowTitle(_translate("dialogo_vehculo", "MainWindow"))
        self.bguardar.setText(_translate("dialogo_vehculo", "Guardar"))
        self.lbplaca.setText(_translate("dialogo_vehculo", "Placa"))
        self.lbmarca.setText(_translate("dialogo_vehculo", "Marca"))
        self.lbdireccion.setText(_translate("dialogo_vehculo", "Número de modelo"))
        self.lbcilindraje.setText(_translate("dialogo_vehculo", "Cilindraje"))
        self.lbciudad_2.setText(_translate("dialogo_vehculo", "Tipo de servicio"))
        self.lbciudad_3.setText(_translate("dialogo_vehculo", "Tipo de combustible"))
        self.lbIdcliente.setText(_translate("dialogo_vehculo", "Id-Cliente"))
        self.lbciudad_4.setText(_translate("dialogo_vehculo", "Capacidad de pasajeros"))
        self.lbciudad.setText(_translate("dialogo_vehculo", "Color"))
        self.lbciudad_6.setText(_translate("dialogo_vehculo", "Númenro de motor"))
        self.lbciudad_5.setText(_translate("dialogo_vehculo", "Número de chasis"))
        self.lbciudad_7.setText(_translate("dialogo_vehculo", "Capacidad de carga"))
