# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\aldo\Documents\GitHub\Proyecto_Concesionario\Agregarvehiculo.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dialogo_vehiculo(object):
    def setupUi(self, dialogo_vehiculo):
        dialogo_vehiculo.setObjectName("dialogo_vehiculo")
        dialogo_vehiculo.setWindowModality(QtCore.Qt.WindowModal)
        dialogo_vehiculo.resize(516, 519)
        self.centralwidget = QtWidgets.QWidget(dialogo_vehiculo)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.lemotor = QtWidgets.QLineEdit(self.centralwidget)
        self.lemotor.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lemotor.sizePolicy().hasHeightForWidth())
        self.lemotor.setSizePolicy(sizePolicy)
        self.lemotor.setObjectName("lemotor")
        self.gridLayout.addWidget(self.lemotor, 11, 2, 1, 1)
        self.bguardar = QtWidgets.QPushButton(self.centralwidget)
        self.bguardar.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bguardar.sizePolicy().hasHeightForWidth())
        self.bguardar.setSizePolicy(sizePolicy)
        self.bguardar.setAutoDefault(False)
        self.bguardar.setDefault(False)
        self.bguardar.setFlat(False)
        self.bguardar.setObjectName("bguardar")
        self.gridLayout.addWidget(self.bguardar, 12, 1, 1, 2)
        self.lbplaca = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbplaca.sizePolicy().hasHeightForWidth())
        self.lbplaca.setSizePolicy(sizePolicy)
        self.lbplaca.setObjectName("lbplaca")
        self.gridLayout.addWidget(self.lbplaca, 1, 0, 1, 1)
        self.lbmarca = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbmarca.sizePolicy().hasHeightForWidth())
        self.lbmarca.setSizePolicy(sizePolicy)
        self.lbmarca.setObjectName("lbmarca")
        self.gridLayout.addWidget(self.lbmarca, 2, 0, 1, 1)
        self.lemarca = QtWidgets.QLineEdit(self.centralwidget)
        self.lemarca.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lemarca.sizePolicy().hasHeightForWidth())
        self.lemarca.setSizePolicy(sizePolicy)
        self.lemarca.setObjectName("lemarca")
        self.gridLayout.addWidget(self.lemarca, 2, 2, 1, 1)
        self.lbmodelo = QtWidgets.QLabel(self.centralwidget)
        self.lbmodelo.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbmodelo.sizePolicy().hasHeightForWidth())
        self.lbmodelo.setSizePolicy(sizePolicy)
        self.lbmodelo.setObjectName("lbmodelo")
        self.gridLayout.addWidget(self.lbmodelo, 3, 0, 1, 2)
        self.ledireccion = QtWidgets.QLineEdit(self.centralwidget)
        self.ledireccion.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ledireccion.sizePolicy().hasHeightForWidth())
        self.ledireccion.setSizePolicy(sizePolicy)
        self.ledireccion.setObjectName("ledireccion")
        self.gridLayout.addWidget(self.ledireccion, 3, 2, 1, 1)
        self.lbcilindraje = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbcilindraje.sizePolicy().hasHeightForWidth())
        self.lbcilindraje.setSizePolicy(sizePolicy)
        self.lbcilindraje.setObjectName("lbcilindraje")
        self.gridLayout.addWidget(self.lbcilindraje, 4, 0, 1, 1)
        self.lecilindraje = QtWidgets.QLineEdit(self.centralwidget)
        self.lecilindraje.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lecilindraje.sizePolicy().hasHeightForWidth())
        self.lecilindraje.setSizePolicy(sizePolicy)
        self.lecilindraje.setObjectName("lecilindraje")
        self.gridLayout.addWidget(self.lecilindraje, 4, 2, 1, 1)
        self.lbtiposervicio = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbtiposervicio.sizePolicy().hasHeightForWidth())
        self.lbtiposervicio.setSizePolicy(sizePolicy)
        self.lbtiposervicio.setObjectName("lbtiposervicio")
        self.gridLayout.addWidget(self.lbtiposervicio, 6, 0, 1, 1)
        self.leservicio = QtWidgets.QLineEdit(self.centralwidget)
        self.leservicio.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leservicio.sizePolicy().hasHeightForWidth())
        self.leservicio.setSizePolicy(sizePolicy)
        self.leservicio.setObjectName("leservicio")
        self.gridLayout.addWidget(self.leservicio, 6, 2, 1, 1)
        self.lbcombustible = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbcombustible.sizePolicy().hasHeightForWidth())
        self.lbcombustible.setSizePolicy(sizePolicy)
        self.lbcombustible.setObjectName("lbcombustible")
        self.gridLayout.addWidget(self.lbcombustible, 7, 0, 1, 2)
        self.lecombustible = QtWidgets.QLineEdit(self.centralwidget)
        self.lecombustible.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lecombustible.sizePolicy().hasHeightForWidth())
        self.lecombustible.setSizePolicy(sizePolicy)
        self.lecombustible.setObjectName("lecombustible")
        self.gridLayout.addWidget(self.lecombustible, 7, 2, 1, 1)
        self.lbIdcliente = QtWidgets.QLabel(self.centralwidget)
        self.lbIdcliente.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbIdcliente.sizePolicy().hasHeightForWidth())
        self.lbIdcliente.setSizePolicy(sizePolicy)
        self.lbIdcliente.setObjectName("lbIdcliente")
        self.gridLayout.addWidget(self.lbIdcliente, 0, 0, 1, 1)
        self.lbpasajeros = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbpasajeros.sizePolicy().hasHeightForWidth())
        self.lbpasajeros.setSizePolicy(sizePolicy)
        self.lbpasajeros.setObjectName("lbpasajeros")
        self.gridLayout.addWidget(self.lbpasajeros, 8, 0, 1, 2)
        self.lepasajeros = QtWidgets.QLineEdit(self.centralwidget)
        self.lepasajeros.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lepasajeros.sizePolicy().hasHeightForWidth())
        self.lepasajeros.setSizePolicy(sizePolicy)
        self.lepasajeros.setObjectName("lepasajeros")
        self.gridLayout.addWidget(self.lepasajeros, 8, 2, 1, 1)
        self.lbcolor = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbcolor.sizePolicy().hasHeightForWidth())
        self.lbcolor.setSizePolicy(sizePolicy)
        self.lbcolor.setObjectName("lbcolor")
        self.gridLayout.addWidget(self.lbcolor, 5, 0, 1, 1)
        self.lecolor = QtWidgets.QLineEdit(self.centralwidget)
        self.lecolor.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lecolor.sizePolicy().hasHeightForWidth())
        self.lecolor.setSizePolicy(sizePolicy)
        self.lecolor.setObjectName("lecolor")
        self.gridLayout.addWidget(self.lecolor, 5, 2, 1, 1)
        self.lenombre = QtWidgets.QLineEdit(self.centralwidget)
        self.lenombre.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lenombre.sizePolicy().hasHeightForWidth())
        self.lenombre.setSizePolicy(sizePolicy)
        self.lenombre.setObjectName("lenombre")
        self.gridLayout.addWidget(self.lenombre, 1, 2, 1, 1)
        self.lbmotor = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbmotor.sizePolicy().hasHeightForWidth())
        self.lbmotor.setSizePolicy(sizePolicy)
        self.lbmotor.setObjectName("lbmotor")
        self.gridLayout.addWidget(self.lbmotor, 11, 0, 1, 2)
        self.lechasis = QtWidgets.QLineEdit(self.centralwidget)
        self.lechasis.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lechasis.sizePolicy().hasHeightForWidth())
        self.lechasis.setSizePolicy(sizePolicy)
        self.lechasis.setObjectName("lechasis")
        self.gridLayout.addWidget(self.lechasis, 9, 2, 1, 1)
        self.lbchasis = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbchasis.sizePolicy().hasHeightForWidth())
        self.lbchasis.setSizePolicy(sizePolicy)
        self.lbchasis.setObjectName("lbchasis")
        self.gridLayout.addWidget(self.lbchasis, 9, 0, 1, 2)
        self.lbcarga = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbcarga.sizePolicy().hasHeightForWidth())
        self.lbcarga.setSizePolicy(sizePolicy)
        self.lbcarga.setObjectName("lbcarga")
        self.gridLayout.addWidget(self.lbcarga, 10, 0, 1, 2)
        self.lecarga = QtWidgets.QLineEdit(self.centralwidget)
        self.lecarga.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lecarga.sizePolicy().hasHeightForWidth())
        self.lecarga.setSizePolicy(sizePolicy)
        self.lecarga.setObjectName("lecarga")
        self.gridLayout.addWidget(self.lecarga, 10, 2, 1, 1)
        self.le_cliente = QtWidgets.QLineEdit(self.centralwidget)
        self.le_cliente.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_cliente.sizePolicy().hasHeightForWidth())
        self.le_cliente.setSizePolicy(sizePolicy)
        self.le_cliente.setObjectName("le_cliente")
        self.gridLayout.addWidget(self.le_cliente, 0, 2, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        dialogo_vehiculo.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(dialogo_vehiculo)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 516, 20))
        self.menubar.setObjectName("menubar")
        dialogo_vehiculo.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(dialogo_vehiculo)
        self.statusbar.setObjectName("statusbar")
        dialogo_vehiculo.setStatusBar(self.statusbar)

        self.retranslateUi(dialogo_vehiculo)
        QtCore.QMetaObject.connectSlotsByName(dialogo_vehiculo)

    def retranslateUi(self, dialogo_vehiculo):
        _translate = QtCore.QCoreApplication.translate
        dialogo_vehiculo.setWindowTitle(_translate("dialogo_vehiculo", "agregar vehículo"))
        self.bguardar.setText(_translate("dialogo_vehiculo", "Guardar"))
        self.lbplaca.setText(_translate("dialogo_vehiculo", "Placa"))
        self.lbmarca.setText(_translate("dialogo_vehiculo", "Marca"))
        self.lbmodelo.setText(_translate("dialogo_vehiculo", "Número de modelo"))
        self.lbcilindraje.setText(_translate("dialogo_vehiculo", "Cilindraje"))
        self.lbtiposervicio.setText(_translate("dialogo_vehiculo", "Tipo de servicio"))
        self.lbcombustible.setText(_translate("dialogo_vehiculo", "Tipo de combustible"))
        self.lbIdcliente.setText(_translate("dialogo_vehiculo", "Id-Cliente"))
        self.lbpasajeros.setText(_translate("dialogo_vehiculo", "Capacidad de pasajeros"))
        self.lbcolor.setText(_translate("dialogo_vehiculo", "Color"))
        self.lbmotor.setText(_translate("dialogo_vehiculo", "Númenro de motor"))
        self.lbchasis.setText(_translate("dialogo_vehiculo", "Número de chasis"))
        self.lbcarga.setText(_translate("dialogo_vehiculo", "Capacidad de carga"))
