# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\aldo\Documents\GitHub\Proyecto_Concesionario\dialogo_contrato.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dialogo_contrato(object):
    def setupUi(self, dialogo_contrato):
        dialogo_contrato.setObjectName("dialogo_contrato")
        dialogo_contrato.resize(459, 497)
        self.centralwidget = QtWidgets.QWidget(dialogo_contrato)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.lecodigo = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lecodigo.sizePolicy().hasHeightForWidth())
        self.lecodigo.setSizePolicy(sizePolicy)
        self.lecodigo.setObjectName("lecodigo")
        self.gridLayout.addWidget(self.lecodigo, 2, 1, 1, 1)
        self.leunidades = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leunidades.sizePolicy().hasHeightForWidth())
        self.leunidades.setSizePolicy(sizePolicy)
        self.leunidades.setObjectName("leunidades")
        self.gridLayout.addWidget(self.leunidades, 3, 1, 1, 1)
        self.lbplaca = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbplaca.sizePolicy().hasHeightForWidth())
        self.lbplaca.setSizePolicy(sizePolicy)
        self.lbplaca.setObjectName("lbplaca")
        self.gridLayout.addWidget(self.lbplaca, 1, 0, 1, 1)
        self.lbidcliente = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbidcliente.sizePolicy().hasHeightForWidth())
        self.lbidcliente.setSizePolicy(sizePolicy)
        self.lbidcliente.setObjectName("lbidcliente")
        self.gridLayout.addWidget(self.lbidcliente, 0, 0, 1, 1)
        self.lbunidades = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbunidades.sizePolicy().hasHeightForWidth())
        self.lbunidades.setSizePolicy(sizePolicy)
        self.lbunidades.setObjectName("lbunidades")
        self.gridLayout.addWidget(self.lbunidades, 3, 0, 1, 1)
        self.leplaca = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leplaca.sizePolicy().hasHeightForWidth())
        self.leplaca.setSizePolicy(sizePolicy)
        self.leplaca.setObjectName("leplaca")
        self.gridLayout.addWidget(self.leplaca, 1, 1, 1, 1)
        self.lbcodigo = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbcodigo.sizePolicy().hasHeightForWidth())
        self.lbcodigo.setSizePolicy(sizePolicy)
        self.lbcodigo.setObjectName("lbcodigo")
        self.gridLayout.addWidget(self.lbcodigo, 2, 0, 1, 1)
        self.leidcliente = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leidcliente.sizePolicy().hasHeightForWidth())
        self.leidcliente.setSizePolicy(sizePolicy)
        self.leidcliente.setObjectName("leidcliente")
        self.gridLayout.addWidget(self.leidcliente, 0, 1, 1, 1)
        self.bguardar = QtWidgets.QPushButton(self.centralwidget)
        self.bguardar.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bguardar.sizePolicy().hasHeightForWidth())
        self.bguardar.setSizePolicy(sizePolicy)
        self.bguardar.setAutoDefault(False)
        self.bguardar.setDefault(False)
        self.bguardar.setFlat(False)
        self.bguardar.setObjectName("bguardar")
        self.gridLayout.addWidget(self.bguardar, 4, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        dialogo_contrato.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(dialogo_contrato)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 459, 21))
        self.menubar.setObjectName("menubar")
        dialogo_contrato.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(dialogo_contrato)
        self.statusbar.setObjectName("statusbar")
        dialogo_contrato.setStatusBar(self.statusbar)

        self.retranslateUi(dialogo_contrato)
        QtCore.QMetaObject.connectSlotsByName(dialogo_contrato)

    def retranslateUi(self, dialogo_contrato):
        _translate = QtCore.QCoreApplication.translate
        dialogo_contrato.setWindowTitle(_translate("dialogo_contrato", "MainWindow"))
        self.lbplaca.setText(_translate("dialogo_contrato", "Placa"))
        self.lbidcliente.setText(_translate("dialogo_contrato", "Id-Cliente"))
        self.lbunidades.setText(_translate("dialogo_contrato", "Unidades contratadas"))
        self.lbcodigo.setText(_translate("dialogo_contrato", "Código del servicio"))
        self.bguardar.setText(_translate("dialogo_contrato", "Guardar"))
