# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\aldo\Documents\GitHub\Proyecto_Concesionario\dialogoservicio.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dialogo_servicio(object):
    def setupUi(self, dialogo_servicio):
        dialogo_servicio.setObjectName("dialogo_servicio")
        dialogo_servicio.resize(627, 456)
        self.centralwidget = QtWidgets.QWidget(dialogo_servicio)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.lehoras = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lehoras.sizePolicy().hasHeightForWidth())
        self.lehoras.setSizePolicy(sizePolicy)
        self.lehoras.setObjectName("lehoras")
        self.gridLayout.addWidget(self.lehoras, 3, 1, 1, 1)
        self.lbNombre = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbNombre.sizePolicy().hasHeightForWidth())
        self.lbNombre.setSizePolicy(sizePolicy)
        self.lbNombre.setObjectName("lbNombre")
        self.gridLayout.addWidget(self.lbNombre, 1, 0, 1, 1)
        self.lbcodigo = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbcodigo.sizePolicy().hasHeightForWidth())
        self.lbcodigo.setSizePolicy(sizePolicy)
        self.lbcodigo.setObjectName("lbcodigo")
        self.gridLayout.addWidget(self.lbcodigo, 0, 0, 1, 1)
        self.lecodigo = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lecodigo.sizePolicy().hasHeightForWidth())
        self.lecodigo.setSizePolicy(sizePolicy)
        self.lecodigo.setObjectName("lecodigo")
        self.gridLayout.addWidget(self.lecodigo, 0, 1, 1, 1)
        self.lbprecio = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbprecio.sizePolicy().hasHeightForWidth())
        self.lbprecio.setSizePolicy(sizePolicy)
        self.lbprecio.setObjectName("lbprecio")
        self.gridLayout.addWidget(self.lbprecio, 2, 0, 1, 1)
        self.leprecio = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leprecio.sizePolicy().hasHeightForWidth())
        self.leprecio.setSizePolicy(sizePolicy)
        self.leprecio.setObjectName("leprecio")
        self.gridLayout.addWidget(self.leprecio, 2, 1, 1, 1)
        self.lbhora = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbhora.sizePolicy().hasHeightForWidth())
        self.lbhora.setSizePolicy(sizePolicy)
        self.lbhora.setObjectName("lbhora")
        self.gridLayout.addWidget(self.lbhora, 3, 0, 1, 1)
        self.bguardar = QtWidgets.QPushButton(self.centralwidget)
        self.bguardar.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bguardar.sizePolicy().hasHeightForWidth())
        self.bguardar.setSizePolicy(sizePolicy)
        self.bguardar.setAutoDefault(False)
        self.bguardar.setDefault(False)
        self.bguardar.setFlat(False)
        self.bguardar.setObjectName("bguardar")
        self.gridLayout.addWidget(self.bguardar, 4, 1, 1, 1)
        self.lenombre = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lenombre.sizePolicy().hasHeightForWidth())
        self.lenombre.setSizePolicy(sizePolicy)
        self.lenombre.setObjectName("lenombre")
        self.gridLayout.addWidget(self.lenombre, 1, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        dialogo_servicio.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(dialogo_servicio)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 627, 20))
        self.menubar.setObjectName("menubar")
        dialogo_servicio.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(dialogo_servicio)
        self.statusbar.setObjectName("statusbar")
        dialogo_servicio.setStatusBar(self.statusbar)

        self.retranslateUi(dialogo_servicio)
        QtCore.QMetaObject.connectSlotsByName(dialogo_servicio)

    def retranslateUi(self, dialogo_servicio):
        _translate = QtCore.QCoreApplication.translate
        dialogo_servicio.setWindowTitle(_translate("dialogo_servicio", "agregar servicio"))
        self.lbNombre.setText(_translate("dialogo_servicio", "Nombre del servicio"))
        self.lbcodigo.setText(_translate("dialogo_servicio", "Código del servicio"))
        self.lbprecio.setText(_translate("dialogo_servicio", "Precio/hora"))
        self.lbhora.setText(_translate("dialogo_servicio", "Horas"))
        self.bguardar.setText(_translate("dialogo_servicio", "Guardar"))
